# Generated by Django 4.0.6 on 2022-09-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_rename_comentario_mensaje_privado_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje_privado',
            name='remitente',
        ),
    ]
