# Generated by Django 4.0.6 on 2022-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_remove_mensaje_privado_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje_privado',
            name='remitente',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='mensaje_privado',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
