# Generated by Django 4.0.6 on 2022-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0004_mensaje_privado_remitente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje_privado',
            name='mensaje',
            field=models.CharField(default='', max_length=150),
        ),
    ]
