# Generated by Django 4.0.6 on 2022-09-04 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajeria', '0006_alter_mensaje_privado_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje_privado',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
