# Generated by Django 4.0.6 on 2022-09-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='f_modificacion',
        ),
    ]
