# Generated by Django 4.0.6 on 2022-09-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comentario_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='comentario',
        ),
    ]
