# Generated by Django 4.0.6 on 2022-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_contenido_comentario_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['f_creacion']},
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Proyecto'), (1, 'Publicado')], default=1),
        ),
    ]
